name: dungeon_and_dorms
description: A new Flutter project.

publish_to: 'none' # Remove this line if you plan to publish

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.1.1
  geolocator: ^14.0.2
  mobile: ^1.2.1
  shared_preferences: ^2.5.3

  # Add any additional packages here

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/login/
    - assets/img/
    - assets/img/boss/andrea/
    - assets/img/boss/shaq/
    - assets/img/boss/gabriel/
    - assets/img/boss/narrator/
    - assets/img/boss/dave/
    - assets/img/boss/adrian/
    - assets/img/backgrounds/
    - assets/img/inventoryItem/
    - assets/img/item/
    - assets/img/item/key/
    - assets/img/item/weapon/
    - assets/img/item/potion/
    - assets/img/MageScrollAnimation/
    - assets/img/playableCharacter/
    - assets/img/playableCharacter/barbarian/
    - assets/img/playableCharacter/barbarian/scroll/
    - assets/img/playableCharacter/barbarian/scroll/animation/
    - assets/img/playableCharacter/bard/
    - assets/img/playableCharacter/bard/scroll/
    - assets/img/playableCharacter/bard/scroll/animation/
    - assets/img/playableCharacter/warlock/
    - assets/img/playableCharacter/warlock/scroll/
    - assets/img/playableCharacter/warlock/scroll/animation/
    - assets/img/playableCharacter/rogue/
    - assets/img/playableCharacter/rogue/scroll/
    - assets/img/playableCharacter/rogue/scroll/animation/
    - assets/gif/


