name: API CI/CD

on:
  push:
    paths:
      - 'api/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Express Backend to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
           sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" <<'EOF'
            cd /var/www

            # If repo doesn't exist, clone it fresh
            if [ ! -d "Dungeon-Dorm/.git" ]; then
              rm -rf Dungeon-Dorm
              git clone https://github.com/anvinas/Dungeon-Dorm.git
            fi

            cd Dungeon-Dorm
            git reset --hard HEAD
            git pull origin main

            # Install deps for the API
            npm install

            # Go back to root and restart server
            pm2 restart server --update-env || pm2 start server.js --name server --update-env
          EOF
