- name: Deploy to server
  env:
    SSH_HOST: ${{ secrets.SSH_HOST }}
    SSH_KEY: ${{ secrets.SSH_KEY }}
    SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
  run: |
    sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" <<'EOF'
      cd /var/www

      if [ ! -d "html/.git" ]; then
        echo "Repo not found. Cloning..."
        rm -rf html
        git clone https://your-repo-url.git html
      fi

      cd html
      git pull origin main
      npm install --omit=dev

      # Restart PM2 or start it if it's not already running
      pm2 restart server || pm2 start index.js --name server
    EOF
