name: API CI/CD

on:
  push:
    paths:
      - 'api/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy Express Backend to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh "${SSH_USERNAME}@${SSH_HOST}" <<'EOF'
            cd /var/www

            if [ ! -d "Dungeon-Dorm/.git" ]; then
              rm -rf Dungeon-Dorm
              git clone https://github.com/anvinas/Dungeon-Dorm.git
            fi

            cd Dungeon-Dorm
            git pull origin main

            cd backend
            npm ci

            pm2 restart server || pm2 start server.js --name server
          EOF
