name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Deploy to Droplet
        env:
          HOST: ${{ secrets.SSH_HOST }}
          USER: ${{ secrets.SSH_USERNAME }}
          SHA: ${{ github.sha }}
        run: |
          ssh -i ~/.ssh/id_rsa $USER@$HOST <<'EOF'
            set -euo pipefail
            cd /var/www/html
            git fetch origin
            git checkout main
            git reset --hard $SHA        # exact commit that triggered the workflow
            npm ci --production
            npm run build
            sudo systemctl reload nginx  # avoid full restart if possible
          EOF
