name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main]

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy React Frontend to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" <<'EOF'
            cd /var/www

            if [ ! -d "Dungeon-Dorm/.git" ]; then
              rm -rf Dungeon-Dorm
              git clone https://github.com/anvinas/Dungeon-Dorm.git
            fi

            cd Dungeon-Dorm
            git pull origin main

            cd frontend
            npm install
            npm run build

            # Deploy to nginx folder
            sudo rm -rf /var/www/html/*
            sudo cp -r build/* /var/www/html/

            # Restart nginx
            sudo systemctl restart nginx
          EOF
