name: Frontend CI/CD

on:
  push:
    paths:
      - 'frontend/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      - name: Deploy Frontend to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_KEY }}  # Note: You're using SSH_KEY as a password
        run: |
          sshpass -p "${SSH_KEY}" ssh -o StrictHostKeyChecking=no "${SSH_USERNAME}@${SSH_HOST}" <<'EOF'
            cd /var/www

            # Clone repo if not present
            if [ ! -d "Dungeon-Dorm/.git" ]; then
              rm -rf Dungeon-Dorm
              git clone https://github.com/anvinas/Dungeon-Dorm.git
            fi

            cd Dungeon-Dorm
            git pull origin main

            cd frontend
            npm install
            npm run build

            # No need to move files if Nginx serves from here:
            # /var/www/Dungeon-Dorm/frontend/dist

            sudo systemctl restart nginx
          EOF
